# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 906a80a6d99a4f41abfca007450c5518bc83e2062a13483245dcab70378e8f186827ef9a0391b2fc8690c61ca1cb72957c6ee0531e0c5e88a9c4e1feb8ef4d4d

test:
  secret_key_base: bd5d34ec5e41b2753c8d36f0b15d407c29989dfaf7d084dae645d31675a14e7ddb2bb7a36dea79f6d50b07961e61258f42d36b720b2e0db0dd77951f54ad8e1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
